---
title: "Precipitation of Fort Collins in Colorado"
author: "AJ"
date: "3/29/2022"
output: html_document
---


```{r download-package, include=FALSE}
library(riem)
library(sf)
library(tidyverse)
library(mapview)
library(USAboundaries)
library(raster)
library(elevatr)
library(tmap)

knitr::opts_chunk$set(echo = TRUE)

```


# Download and data check

```{r}
network <- riem_networks()

co_stations <- riem_stations(network = "CO_ASOS") %>%
  st_as_sf(., coords=c('lon', 'lat'), crs=4326)

glimpse(co_stations)

```

## Interactive map 
```{r}
# mapview(co_stations)

# Download some state boudary data

co_count <- us_counties(states = "Colorado")

co_elev <- elevatr::get_elev_raster(co_stations, z=9)

mapview(co_count) + mapview(co_elev) + mapview(co_stations)

```

## Static map
```{r}
tm_shape(co_count) + tm_polygons(col='white') + tm_shape(co_stations) + tm_bubbles(size=0.2, col='red')

```


# Download a single site data and analyze the precipitation
```{r}
fnl <- riem_measures(station = 'FNL',
                   date_start = '1987-05-01',
                   date_end = '2000-05-01')
daily <- fnl %>%
  mutate(date = as.Date(valid)) %>%
  group_by(date) %>%
  summarize(daily_rain = mean(p01i*24,na.rm=T))

ggplot(daily, aes(x=date, y = daily_rain)) + 
  geom_point() +
  scale_y_log10() +
  labs(x="Year", y="Daily rain (inch)", title = "Daily Rain of Fort Collins")





```

